"""
load_to_database.py  —  Step 3 of the invoice-ocr-pipeline
===========================================================
Reads data/extracted_invoices.csv and loads it into the SQLite database,
initialising the schema from schema.sql if the tables don't exist yet.

Phase 1: error handling, logging, schema-from-sql, env-var config.
Phase 2:
  - INSERT OR IGNORE: running the script twice won't create duplicate rows.
    Relies on the UNIQUE constraint on invoice_id defined in schema.sql.
  - validation_passed and validation_note columns are now included in the
    INSERT statement, persisting the anomaly flags from the extraction step.
  - Post-load summary query reports total count, flagged rows, and
    total/average expenditure.
"""

import logging
import os
import sqlite3
from pathlib import Path

import pandas as pd
from dotenv import load_dotenv

# ---------------------------------------------------------------------------
# Bootstrap
# ---------------------------------------------------------------------------
load_dotenv()

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s — %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
logger = logging.getLogger("load_to_database")

# ---------------------------------------------------------------------------
# Configuration
# ---------------------------------------------------------------------------
EXTRACTED_CSV = Path(os.getenv("EXTRACTED_CSV", "data/extracted_invoices.csv"))
DB_PATH       = Path(os.getenv("DB_PATH",       "data/finance_system.db"))
SCHEMA_PATH   = Path(os.getenv("SCHEMA_PATH",   "schema.sql"))

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _init_schema(conn: sqlite3.Connection) -> None:
    """Apply schema.sql to the open connection (idempotent DROP/CREATE)."""
    if not SCHEMA_PATH.exists():
        raise FileNotFoundError(
            f"schema.sql not found at '{SCHEMA_PATH}'. "
            "Ensure it exists in the project root."
        )
    conn.executescript(SCHEMA_PATH.read_text(encoding="utf-8"))
    logger.info("Schema applied from %s.", SCHEMA_PATH)


def _load_csv(csv_path: Path) -> pd.DataFrame:
    """Read and lightly validate the extracted CSV."""
    if not csv_path.exists():
        raise FileNotFoundError(
            f"Extracted CSV not found: '{csv_path}'. "
            "Run extract_ocr_data.py first."
        )
    df = pd.read_csv(csv_path)

    required = {
        "invoice_id", "invoice_date", "vendor_name",
        "subtotal", "tax_amount", "grand_total", "source_file",
    }
    missing = required - set(df.columns)
    if missing:
        raise ValueError(
            f"CSV is missing expected columns: {', '.join(sorted(missing))}"
        )

    # Phase 2 columns may be absent if CSV was generated by a Phase 1 script;
    # default them so the INSERT always has values.
    if "validation_passed" not in df.columns:
        df["validation_passed"] = 1
    if "validation_note" not in df.columns:
        df["validation_note"] = ""

    return df


# ---------------------------------------------------------------------------
# Core loader
# ---------------------------------------------------------------------------

def load_records(conn: sqlite3.Connection, df: pd.DataFrame) -> tuple[int, int]:
    """
    Insert each DataFrame row into processed_invoices using INSERT OR IGNORE.

    INSERT OR IGNORE silently skips any row whose invoice_id already exists
    (UNIQUE constraint), making the load step fully idempotent.

    Returns (inserted_count, skipped_count).
    """
    cursor   = conn.cursor()
    inserted = skipped = 0

    # Count rows currently in table to detect skips after bulk insert.
    before = conn.execute("SELECT COUNT(*) FROM processed_invoices").fetchone()[0]

    for _, row in df.iterrows():
        try:
            cursor.execute(
                """
                INSERT OR IGNORE INTO processed_invoices (
                    invoice_id, invoice_date, vendor_name,
                    subtotal, tax_amount, grand_total,
                    validation_passed, validation_note, source_file
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    row.get("invoice_id"),
                    row.get("invoice_date"),
                    row.get("vendor_name"),
                    row.get("subtotal")    if pd.notna(row.get("subtotal"))    else None,
                    row.get("tax_amount")  if pd.notna(row.get("tax_amount"))  else None,
                    row.get("grand_total") if pd.notna(row.get("grand_total")) else None,
                    int(row.get("validation_passed", 1)),
                    row.get("validation_note", "") or "",
                    row.get("source_file"),
                ),
            )
            # rowcount is 1 for a real insert, 0 for an IGNORE'd duplicate.
            if cursor.rowcount == 1:
                inserted += 1
                logger.info("  [INSERT] %s", row.get("invoice_id", "?"))
            else:
                skipped += 1
                logger.info("  [SKIP]   %s — already in DB",
                            row.get("invoice_id", "?"))

        except sqlite3.Error as exc:
            logger.error("  [FAIL]   %s — DB error: %s",
                         row.get("invoice_id", "?"), exc)

    conn.commit()
    return inserted, skipped


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    logger.info("Starting database load — %s → %s", EXTRACTED_CSV, DB_PATH)

    DB_PATH.parent.mkdir(parents=True, exist_ok=True)

    # Fail fast on CSV problems before touching the DB.
    try:
        df = _load_csv(EXTRACTED_CSV)
    except (FileNotFoundError, ValueError) as exc:
        logger.error("Cannot load CSV: %s", exc)
        return

    logger.info("Read %d row(s) from CSV.", len(df))

    try:
        with sqlite3.connect(DB_PATH) as conn:
            _init_schema(conn)
            inserted, skipped = load_records(conn, df)
    except FileNotFoundError as exc:
        logger.error("Schema error: %s", exc)
        return
    except sqlite3.Error as exc:
        logger.error("Unrecoverable database error: %s", exc)
        return

    logger.info("Load complete — %d inserted, %d skipped (duplicates).",
                inserted, skipped)

    # ── Post-load summary ─────────────────────────────────────────────────
    try:
        with sqlite3.connect(DB_PATH) as conn:
            row = conn.execute(
                """
                SELECT
                    COUNT(*)              AS total_rows,
                    SUM(grand_total)      AS total_spend,
                    AVG(grand_total)      AS avg_invoice,
                    SUM(CASE WHEN validation_passed = 0 THEN 1 ELSE 0 END)
                                          AS flagged_rows
                FROM processed_invoices
                """
            ).fetchone()

            total_rows, total_spend, avg_invoice, flagged = row
            logger.info(
                "DB summary — total rows: %d | spend: Rs. %s | avg: Rs. %s | "
                "flagged: %d",
                total_rows or 0,
                f"{total_spend:,.2f}" if total_spend else "0.00",
                f"{avg_invoice:,.2f}" if avg_invoice else "0.00",
                flagged or 0,
            )
            if flagged:
                logger.warning(
                    "%d row(s) have validation_passed=0. "
                    "Query: SELECT * FROM processed_invoices "
                    "WHERE validation_passed = 0;",
                    flagged,
                )
    except sqlite3.Error as exc:
        logger.warning("Could not run summary query: %s", exc)


if __name__ == "__main__":
    main()